// <auto-generated />
using System;
using CONSEGO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CONSEGO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427222456_CompletarUsuariosYRoles")]
    partial class CompletarUsuariosYRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CONSEGO.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CONSEGO.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Criticidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Plataformas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "GitHub Organization",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "AWS",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "Azure",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "VMs On-Premise",
                            Tipo = "Infra"
                        });
                });

            modelBuilder.Entity("CONSEGO.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso total",
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Revisa solicitudes",
                            Nombre = "AnalistaSeguridad"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Crea solicitudes",
                            Nombre = "Solicitante"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Implementa accesos",
                            Nombre = "Infra"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Solo lectura y revisión de logs",
                            Nombre = "Auditor"
                        });
                });

            modelBuilder.Entity("CONSEGO.Models.SolicitudAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacionesSeguridad")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAcceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PlataformaId");

                    b.HasIndex("UsuarioSolicitanteId");

                    b.ToTable("SolicitudesAcceso");
                });

            modelBuilder.Entity("CONSEGO.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Administrador",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "analista@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana García",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "solicitante@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan Asto",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "auditor@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro Castro",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 5
                        });
                });

            modelBuilder.Entity("CONSEGO.Models.SolicitudAcceso", b =>
                {
                    b.HasOne("CONSEGO.Models.Usuario", "Analista")
                        .WithMany("SolicitudesComoAnalista")
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CONSEGO.Models.Plataforma", "Plataforma")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CONSEGO.Models.Usuario", "UsuarioSolicitante")
                        .WithMany("SolicitudesComoSolicitante")
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Plataforma");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("CONSEGO.Models.Usuario", b =>
                {
                    b.HasOne("CONSEGO.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CONSEGO.Models.Plataforma", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("CONSEGO.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CONSEGO.Models.Usuario", b =>
                {
                    b.Navigation("SolicitudesComoAnalista");

                    b.Navigation("SolicitudesComoSolicitante");
                });
#pragma warning restore 612, 618
        }
    }
}
