// <auto-generated />
using System;
using CONSEGO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CONSEGO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403155345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CONSEGO.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Criticidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Plataformas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "GitHub Organization",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "AWS",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "Azure",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 4,
                            Activa = true,
                            Criticidad = "Media",
                            Nombre = "Microsoft 365",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 5,
                            Activa = true,
                            Criticidad = "Media",
                            Nombre = "Cloudflare",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 6,
                            Activa = true,
                            Criticidad = "Baja",
                            Nombre = "WordPress",
                            Tipo = "App"
                        },
                        new
                        {
                            Id = 7,
                            Activa = true,
                            Criticidad = "Media",
                            Nombre = "GoDaddy",
                            Tipo = "Cloud"
                        },
                        new
                        {
                            Id = 8,
                            Activa = true,
                            Criticidad = "Alta",
                            Nombre = "VMs On-Premise",
                            Tipo = "Infra"
                        });
                });

            modelBuilder.Entity("CONSEGO.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Administrador del sistema con acceso total",
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Analista de seguridad que revisa solicitudes",
                            Nombre = "AnalistaSeguridad"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Usuario que crea solicitudes de acceso",
                            Nombre = "Solicitante"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Equipo de infraestructura que implementa accesos aprobados",
                            Nombre = "Infra"
                        });
                });

            modelBuilder.Entity("CONSEGO.Models.SolicitudAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalistaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ObservacionesSeguridad")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAcceso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioSolicitanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnalistaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("PlataformaId");

                    b.HasIndex("UsuarioSolicitanteId");

                    b.ToTable("SolicitudesAcceso");
                });

            modelBuilder.Entity("CONSEGO.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Administrador",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "analista@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana García (Analista)",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "solicitante@idmtechnology.pe",
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos López (Solicitante)",
                            PasswordHash = "WIxV884rhWmxU8WrvxP590MIuIogAXzGmbg1zJMZXRY=",
                            RolId = 3
                        });
                });

            modelBuilder.Entity("CONSEGO.Models.SolicitudAcceso", b =>
                {
                    b.HasOne("CONSEGO.Models.Usuario", "Analista")
                        .WithMany("SolicitudesComoAnalista")
                        .HasForeignKey("AnalistaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CONSEGO.Models.Plataforma", "Plataforma")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CONSEGO.Models.Usuario", "UsuarioSolicitante")
                        .WithMany("SolicitudesComoSolicitante")
                        .HasForeignKey("UsuarioSolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("Plataforma");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("CONSEGO.Models.Usuario", b =>
                {
                    b.HasOne("CONSEGO.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CONSEGO.Models.Plataforma", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("CONSEGO.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CONSEGO.Models.Usuario", b =>
                {
                    b.Navigation("SolicitudesComoAnalista");

                    b.Navigation("SolicitudesComoSolicitante");
                });
#pragma warning restore 612, 618
        }
    }
}
